import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./components/organism/navbar"
import Footer from "./components/organism/footer"
import { QueryProvider } from "./components/molecule/query-provider"
import PopUpContextProvider from "./context/pop-up"
import { ReactNode } from "react"
import Toast from "./components/molecule/toast"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
        <PopUpContextProvider>
      <body className={`${inter.className} relative min-h-screen h-full`}>
        <Toast />
          <QueryProvider>
            <Navbar />
            <div className="px-5">{children}</div>
            <Footer />
          </QueryProvider>
      </body>
      </PopUpContextProvider>
    </html>
  )
}
