import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/organism/navbar'
import Footer from './components/organism/footer'
import { Inder } from "next/font/google"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen h-full`}>
        <Navbar />
        <div className='px-5'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
